name: to_do_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  device_preview: ^1.1.0
  flutter_screenutil: ^5.8.4
  zoom_tap_animation: ^1.1.0

  sqflite: ^2.2.8+4

  shared_preferences: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/svg/add-task-icons/
    - assets/svg/arrow-icons-all/
    - assets/svg/bottom-nav-bar-icons/
    - assets/svg/calendar-s-icons/
    - assets/svg/category-icons/
    - assets/svg/menu-icons/
    - assets/svg/setting-page-icons/
    - assets/svg/task-page-icons/
    - assets/svg/urgent_colorful_icons/


  fonts:
   - family: Roboto
     fonts:
       - asset: assets/fonts/Roboto-Black.ttf
       - asset: assets/fonts/Roboto-BlackItalic.ttf
       - asset: assets/fonts/Roboto-Bold.ttf
       - asset: assets/fonts/Roboto-BoldItalic.ttf
       - asset: assets/fonts/Roboto-Italic.ttf
       - asset: assets/fonts/Roboto-Light.ttf
       - asset: assets/fonts/Roboto-LightItalic.ttf
       - asset: assets/fonts/Roboto-Medium.ttf
       - asset: assets/fonts/Roboto-MediumItalic.ttf
       - asset: assets/fonts/Roboto-Regular.ttf
       - asset: assets/fonts/Roboto-Thin.ttf
       - asset: assets/fonts/Roboto-ThinItalic.ttf
       
